#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Nov 06 15:40:35 EET 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim uart_transmitter_tb_time_synth -key {Post-Synthesis:sim_1:Timing:uart_transmitter_tb} -tclbatch uart_transmitter_tb.tcl -view /home/billm123/digsys-project-2/PartB/uart_transmitter_tb_func_synth.wcfg -log simulate.log"
xsim uart_transmitter_tb_time_synth -key {Post-Synthesis:sim_1:Timing:uart_transmitter_tb} -tclbatch uart_transmitter_tb.tcl -view /home/billm123/digsys-project-2/PartB/uart_transmitter_tb_func_synth.wcfg -log simulate.log

